export const auditCategoryValues = [
  "authentication",
  "membership",
  "authorization",
  "organization",
  "office",
  "project",
  "service_type",
  "technician",
  "work_order",
  "dispatch_assignment",
  "system",
] as const;

export type AuditCategory = (typeof auditCategoryValues)[number];

export const auditOutcomeValues = ["succeeded", "denied", "failed"] as const;

export type AuditOutcome = (typeof auditOutcomeValues)[number];

export const auditTargetTypeValues = [
  "organization",
  "office",
  "user",
  "membership",
  "project",
  "service_type",
  "technician",
  "technician_office_eligibility",
  "work_order",
  "dispatch_assignment",
  "assignment_technician",
] as const;

export type AuditTargetType = (typeof auditTargetTypeValues)[number];

export const auditActionValues = [
  "membership.prepared",
  "membership.role_changed",
  "membership.status_changed",
  "membership.suspended",
  "membership.revoked",
  "membership.office_policy_changed",
  "office_access.assigned",
  "office_access.removed",
  "project.created",
  "project.updated",
  "project.status_changed",
  "project.archived",
  "service_type.created",
  "service_type.updated",
  "service_type.status_changed",
  "technician.created",
  "technician.updated",
  "technician.status_changed",
  "technician.membership_linked",
  "technician.membership_unlinked",
  "technician.office_eligibility_added",
  "technician.office_eligibility_removed",
  "work_order.created",
  "work_order.updated",
  "work_order.status_changed",
  "work_order.cancelled",
  "dispatch_assignment.created",
  "dispatch_assignment.schedule_changed",
  "dispatch_assignment.primary_assigned",
  "dispatch_assignment.primary_reassigned",
  "dispatch_assignment.primary_removed",
  "dispatch_assignment.support_added",
  "dispatch_assignment.support_removed",
  "dispatch_assignment.acknowledged",
  "dispatch_assignment.started",
  "dispatch_assignment.completed",
  "dispatch_assignment.cancelled",
  "dispatch_assignment.conflict_overridden",
  "authorization.cross_office_mutation_denied",
  "authorization.conflict_override_denied",
  "authorization.membership_administration_denied",
  "authorization.own_assignment_access_denied",
] as const;

export type AuditAction = (typeof auditActionValues)[number];

export const auditActionCategory: Record<AuditAction, AuditCategory> = {
  "membership.prepared": "membership",
  "membership.role_changed": "membership",
  "membership.status_changed": "membership",
  "membership.suspended": "membership",
  "membership.revoked": "membership",
  "membership.office_policy_changed": "membership",
  "office_access.assigned": "office",
  "office_access.removed": "office",
  "project.created": "project",
  "project.updated": "project",
  "project.status_changed": "project",
  "project.archived": "project",
  "service_type.created": "service_type",
  "service_type.updated": "service_type",
  "service_type.status_changed": "service_type",
  "technician.created": "technician",
  "technician.updated": "technician",
  "technician.status_changed": "technician",
  "technician.membership_linked": "technician",
  "technician.membership_unlinked": "technician",
  "technician.office_eligibility_added": "technician",
  "technician.office_eligibility_removed": "technician",
  "work_order.created": "work_order",
  "work_order.updated": "work_order",
  "work_order.status_changed": "work_order",
  "work_order.cancelled": "work_order",
  "dispatch_assignment.created": "dispatch_assignment",
  "dispatch_assignment.schedule_changed": "dispatch_assignment",
  "dispatch_assignment.primary_assigned": "dispatch_assignment",
  "dispatch_assignment.primary_reassigned": "dispatch_assignment",
  "dispatch_assignment.primary_removed": "dispatch_assignment",
  "dispatch_assignment.support_added": "dispatch_assignment",
  "dispatch_assignment.support_removed": "dispatch_assignment",
  "dispatch_assignment.acknowledged": "dispatch_assignment",
  "dispatch_assignment.started": "dispatch_assignment",
  "dispatch_assignment.completed": "dispatch_assignment",
  "dispatch_assignment.cancelled": "dispatch_assignment",
  "dispatch_assignment.conflict_overridden": "dispatch_assignment",
  "authorization.cross_office_mutation_denied": "authorization",
  "authorization.conflict_override_denied": "authorization",
  "authorization.membership_administration_denied": "authorization",
  "authorization.own_assignment_access_denied": "authorization",
};

export const securityAuditCategories = [
  "authentication",
  "membership",
  "authorization",
  "organization",
  "office",
  "system",
] as const satisfies readonly AuditCategory[];
